//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PresentationWebSite.UI.WebMvc.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Développeur .Net.
        /// </summary>
        public static string APPLICATION_OWNER_JOB {
            get {
                return ResourceManager.GetString("APPLICATION_OWNER_JOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to François GONZALEZ.
        /// </summary>
        public static string APPLICATION_OWNER_NAME {
            get {
                return ResourceManager.GetString("APPLICATION_OWNER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diplômes.
        /// </summary>
        public static string INTRODUCTION_HEADER_GRADUATIONS {
            get {
                return ResourceManager.GetString("INTRODUCTION_HEADER_GRADUATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loisirs.
        /// </summary>
        public static string INTRODUCTION_HEADER_HOBBIES {
            get {
                return ResourceManager.GetString("INTRODUCTION_HEADER_HOBBIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emplois.
        /// </summary>
        public static string INTRODUCTION_HEADER_JOBS {
            get {
                return ResourceManager.GetString("INTRODUCTION_HEADER_JOBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compétences.
        /// </summary>
        public static string INTRODUCTION_HEADER_SKILLS {
            get {
                return ResourceManager.GetString("INTRODUCTION_HEADER_SKILLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        public static string NAVBAR_MENU_HOME_HEADER {
            get {
                return ResourceManager.GetString("NAVBAR_MENU_HOME_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordonnées.
        /// </summary>
        public static string NAVBAR_MENU_INFORMATION_HEADER {
            get {
                return ResourceManager.GetString("NAVBAR_MENU_INFORMATION_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Présentation - C.V..
        /// </summary>
        public static string NAVBAR_MENU_INTRODUCTION_HEADER {
            get {
                return ResourceManager.GetString("NAVBAR_MENU_INTRODUCTION_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue.
        /// </summary>
        public static string NAVBAR_MENU_LANGUAGE_HEADER {
            get {
                return ResourceManager.GetString("NAVBAR_MENU_LANGUAGE_HEADER", resourceCulture);
            }
        }
    }
}
